name: Profile_Update
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  # push: {branches: ["master"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: 🥰 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_API }}

          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: python
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_languages_other: yes
          
      - name: 🥰 Addon
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: addon.svg
          token: ${{ secrets.METRICS_API }}

          # Options
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_fortune: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_repositories: 100
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_repositories_featured: Jint-lzxy/SPFbase, Jint-lzxy/SPFlib, Jint-lzxy/nvimconfig

      - name: 🥰 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_API }}

          # Options
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          # plugin_achievements_threshold: C
