name: Update assets
on:
  # push: {branches: ["master"]}
  # Scheduled update (every day)
  schedule: [{ cron: "00 16 * * *" }]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🥂 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          committer_message: "[Actions] chore: update ${filename}"
          token: ${{ secrets.METRICS_API }}

          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Taipei
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_reactions: yes
          plugin_reactions_limit: 120
          plugin_reactions_display: absolute
          plugin_reactions_details: percentage
          plugin_languages: yes
          plugin_languages_ignored: python, html
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_languages_other: yes

      - name: 🥂 Addon
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: addon.svg
          committer_message: "[Actions] chore: update ${filename}"
          token: ${{ secrets.METRICS_API }}

          # Options
          template: classic
          base: ""
          config_timezone: Asia/Taipei
          plugin_fortune: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 350
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_days: 5
          plugin_code_lines: 20
          plugin_code_languages: c, c++, lua, swift, objective-c, objective-c++, hlsl, javascript
          plugin_code_visibility: public
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_repositories: 100
          plugin_repositories_featured: Jint-lzxy/nvimconfig, freebsd/freebsd-src, llvm/llvm-project, Jint-lzxy/SPFbase
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          # plugin_achievements_threshold: C

      - name: 🥂 Setup repo
        uses: actions/checkout@v4
      - name: 🥂 Reorganize resources
        run: |
          git pull --no-edit && for img in *.svg; do mv -fv "${img}" ./resources/svg/; done

      - name: 🥂 Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Actions] chore: reorganize assets"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          file_pattern: "*.svg"
